server:
  error:
    include-stacktrace: never

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/AnimeDataBase?createDatabaseIfNotExist=true
    username: postgres
    password: Aquino#123
  jpa:
    hibernate:
      ddlAuto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
