server:
  error:
    include-stacktrace: never

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/anime?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: postgres
    password: Aquino#123
  jpa:
    hibernate:
      ddlAuto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect